settings:
  message-prefix: MiniGameWorld
  backup-data-save-delay: 60
  debug-mode: true
  isolated-chat: true
  isolated-join-quit-message: false
  join-sign-caption: '[MiniGame]'
  leave-sign-caption: '[Leave MiniGame]'
  scoreboard: true
  scoreboard-update-delay: 10
  remove-not-necessary-keys: false
  min-leave-time: 3
  start-sound: BLOCK_END_PORTAL_SPAWN
  finish-sound: ENTITY_ENDER_DRAGON_DEATH
