settings:
  message-prefix: §lMiniGameWorld§r
  backup-data-save-delay: 60
  debug-mode: true
  isolated-chat: true
  isolated-join-quit-message: false
  join-sign-caption: '[MiniGame]'
  leave-sign-caption: '[Leave MiniGame]'
  scoreboard: true
  scoreboard-update-delay: 10
  remove-not-necessary-keys: false
